#BANNER
banner:
  location: classpath:/banner/banner.txt
  
#CONFIGURACION DATABASE Y HIBERNATE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #limpia si se borro un campo en la base de datos
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect